### PR TITLE
Interfaced relations fix

### LINKED ISSUE #182: [Question/Suggestion] Autogeneration of Mutations for relations to Interface types
question: What is the best practice for resolving Mutations for interfaced types?

Example schema:

```
interface LegalPerson {
	identifier: ID
	name: String!
}

type Person implements LegalPerson {
	identifier: ID
	name: String!
	birthDate: Date
}

type Organization implements LegalPerson  {
	identifier: ID
	name: String!
	foundingDate: Date
}

type CreativeWork {
	identifier: ID
	title: String!
	author: LegalPerson
	responsiblePerson: Person
	publicRepository: Organization
} 
```

The _makeAugmentedSchema()_ function will autogenerate **AddCreativeWorkResponsiblePerson** and **AddCreativeWorkPublicRepository** mutations and resolvers.

But it will **not** autogenerate the **AddCreativeWorkAuthor** mutation and resolver.

——————————

So far I’ve come up with something along these lines:

```
type Mutation {
  AddCreativeWorkAuthor(from:_CreativeWorkInterfaceInput, to:_LegalPersonInput): _AddLegalPersonPayload
}

input _LegalPersonInput {
  identifier: ID!
  type: LegalPersonType!
}

type _AddLegalPersonPayload {
  from: CreativeWork
  to: LegalPerson
}

enum LegalPersonType {
  Person
  Organization
}

Mutation: {
  AddCreativeWorkAuthor (object, params, ctx, resolveInfo) {
    let session = driver.session();
    let query = "MATCH (`creativeWork_from`:`" + params.from.type + "` {identifier: $from.identifier})” +
      " MATCH (`legalPerson_to`: `" + params.to.type + "` {identifier: $to. identifier})" +
      " CREATE (`creativeWork_from`)-[`author_relation`:`AUTHOR`]->(`legalPerson_to`)" +
      " RETURN { from: `creativeWork_from` ,to: `legalPerson_to` } AS `_AddLegalPersonPayload`;"

    let promise = session.run(query, params)
      .then( result => {
        let rt = result.records.map(record => {
          let data = record.get("_AddLegalPersonPayload");
          return {from:data.from.properties, to:data.to.properties};
        });

        return rt[0];
      })
      .catch(function (error) {console.log(error);});

    return promise;
  }
}
```

But this feels quite cumbersome;
Plus: my schema has many interfaced types, some of which will also need relations to other interfaced/unioned types - adding another layer of complications

There must be a better way

—————————————

Could, maybe, a solution be found on the basis of [this proposal](
https://github.com/neo4j-graphql/neo4j-graphql-js/issues/150)?:

If a node would carry the Interface (or Union) label(s) as well, it might be possible to autogenerate the Add/Update/Delete resolvers for relations to/from Interface/Union types.
This could only work if the identifier ID is globally unique, as [proposed](
https://graphql.org/learn/caching/#globally-unique-ids) in the GraphQL specification.

As it would be able to autogenerate an _AddCreativeWorkAuthor_ mutation resolver with a cypher query like this:

```
MATCH (`creativeWork_from`:`CreativeWork` {identifier: $from.identifier})
      	MATCH (`legalPerson_to`:`LegalPerson` {identifier: $to.identifier)
      	CREATE (`creativeWork_from`)-[`author_relation`:`AUTHOR`]->(`legalPerson_to `)
      	RETURN `author_relation` { from: `creativeWork_from ` { .title } ,to: `legalPerson_to ` { .name }  } AS `_AddLegalPersonPayload `;
```

### PR DESCRIPTION
**Pull request by ChristiaanScheermeijer**
Hi,

This is my first PR to this repository. The code is quite complex so I can't oversee all edge cases regarding these changes. 

This PR will fix relation mutations with interfaced types. Given the following schema:

```
interface Person {
  userId: ID!
  name: String
}

type User implements Person {
  userId: ID!
  name: String
}

type Actor implements Person {
  userId: ID!
  name: String
  awards: Int
}

type Movie {
  movieId: ID!
  actors: [Actor] @relation(name: "ACTORS", direction: "OUT")
  seenBy: Person @relation(name: "SEEN_BY", direction: "OUT")
}
```

The following query will work:

```
mutation {
  AddMovieSeenBy(
    from: { movieId: "123" },
    to: { userId: "456" }
  ) {
    from {
      movieId
    }
    to {
      name
      ... on Actor {
        awards
      }
    }
  }
}
```

Happy to hear your feedback!

Fixed #182

### CODE REVIEW

File: example/apollo-server/movies.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import { augmentTypeDefs, augmentSchema } from '../../src/index';
 import { ApolloServer, gql, makeExecutableSchema } from 'apollo-server';
-import { v1 as neo4j } from 'neo4j-driver';
+import neo4j from 'neo4j-driver';
```
Comment (ChristiaanScheermeijer) [inline example/apollo-server/movies.js]: I'm not sure if this should be in this pull request, but the example server didn't work for on the master branch.

**Comment by johnymontana** [comment]
Looks good. Thanks @ChristiaanScheermeijer!

File: example/apollo-server/movies.js (hunk 1 above)
Comment (johnymontana) [reply example/apollo-server/movies.js]: This is a result of upgrading the version of neo4j-driver, which removes the v1 namespace. I was lazy and only updated movies-middleware.js which is why this one was failing. My fault.
